# Generated by Django 2.2.7 on 2020-01-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='User',
        ),
    ]
